#!/bin/bash

## Set up suffix for adjoint run: "_ad"
#  or leave as "" for forward run
suff=""
ecco_suff=""
build_suff=

## Set up directories
root_dir=$WORK/eccov4-euc/MITgcm
exp_dir=$PWD
build_dir=$exp_dir/build$suff$ecco_suff$build_suff
code_dir=$exp_dir/code$suff$build_suff
ecco_code=$exp_dir/code$ecco_suff

## Opt file architecture specific
skylake_opt=$computing/optfiles/linux_amd64_ifort+mpi_stampede2_skx

## Use the correct opt file here
if [[ $suff == "_ftl" ]] ; then
    build_cmd="$root_dir/tools/genmake2 -rd=$root_dir -mods='$code_dir $ecco_code' -optfile=$skylake_opt -mpi"
else
    build_cmd="$root_dir/tools/genmake2 -rd=$root_dir -mods=$ecco_code -optfile=$skylake_opt -mpi"
fi
#tmp="make_junk"$suff".txt"

## Build the model in build directory
if [ ! -d $build_dir ]
  then
        mkdir $build_dir
        cd $build_dir
else
        cd $build_dir
        if [ -s Makefile ] ; then
		make clean
	fi
fi

cd $build_dir
echo "Inside dir: "$PWD

echo "Evaluating: "$build_cmd
eval $build_cmd 
echo "Make depend ..."
eval "make depend" 
echo "Making executable ..."
if [[ $suff == "_ad" ]] ; then
  eval "make -j 8 adall" 
elif [[ $suff == '_ftl' ]] ; then
  eval "make -j 8 ftlall" 
else
  eval "make -j 8"
fi
