#!/bin/bash

#SBATCH -J eucv4r4140W
#SBATCH -o eucv4r4140W.%j.out
#SBATCH -e eucv4r4140W.%j.err
#SBATCH -N 2
#SBATCH -n 96
#SBATCH -p skx-normal
#SBATCH -t 10:00:00
#SBATCH -A Polar-Project

#SBATCH --mail-user=timsmith204@utexas.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

export workrun=

ibrun -np 96 tacc_affinity ./mitgcmuv

cp STDOUT.0000 $workrun
cp -r ${SLURM_JOB_NAME}* $workrun
cp euc_out* $workrun
