#!/bin/bash

#SBATCH -J eucv4r4140W
#SBATCH -o eucv4r4140W.%j.out
#SBATCH -e eucv4r4140W.%j.err
#SBATCH -N 4
#SBATCH -n 192
#SBATCH -p skx-dev
#SBATCH -t 2:00:00
#SBATCH -A Polar-Project

#SBATCH --mail-user=timsmith204@utexas.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

export workrun=

ibrun -np 192 tacc_affinity ./mitgcmuv

cp STDOUT.0000 $workrun
cp -r diags $workrun
cp -r ${SLURM_JOB_NAME}* $workrun
cp pickup* $workrun
cp euc_out* $workrun
